services:
  - type: web
    name: watchwithme-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: watchwithme-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: ADMIN_USERNAME
        value: Hari0mSuman
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        value: hariom@watchwithme.com
      - key: ADMIN_FIRST_NAME
        value: Hariom
      - key: ADMIN_LAST_NAME
        value: Suman
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: watchwithme-db
    databaseName: watchwithme
    user: watchwithme 
