services:
  - type: web
    name: watchwithme-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: watchwithme-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: watchwithme-db
    databaseName: watchwithme
    user: watchwithme 